version: "3.9"

services:
  app:
    build: .
    container_name: supersl2-app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - BASE_SAVE_DIR=/app/storage
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./credentials.json:/app/credentials.json:ro
    restart: unless-stopped

